- name: ArgoCD | Deploy Sealed Secret Master Key
  run_once: yes
  delegate_to: localhost
  environment:
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig_file | default('~/.kube/config') }}"
    KUBECONFIG: "{{ kubeconfig_file | default('~/.kube/config') }}"
  when: sealed_secrets_key is defined
  community.kubernetes.k8s:
    state: "{{ argocd_action | default('present') }}"
    definition: "{{ sealed_secrets_key }}"




